"""feeders use disco_code fk

Revision ID: 02314e4324a0
Revises: 8d9fbd3bc6ad
Create Date: 2026-03-25 12:47:47.476055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '02314e4324a0'
down_revision: Union[str, None] = '8d9fbd3bc6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discos_code_key', 'discos', type_='unique')
    op.create_index(op.f('ix_discos_code'), 'discos', ['code'], unique=True)
    op.add_column('feeders', sa.Column('disco_code', sa.String(length=10), nullable=False))
    op.drop_constraint('feeders_disco_id_fkey', 'feeders', type_='foreignkey')
    op.create_foreign_key(None, 'feeders', 'discos', ['disco_code'], ['code'])
    op.drop_column('feeders', 'disco_id')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('feeders', sa.Column('disco_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feeders', type_='foreignkey')
    op.create_foreign_key('feeders_disco_id_fkey', 'feeders', 'discos', ['disco_id'], ['id'])
    op.drop_column('feeders', 'disco_code')
    op.drop_index(op.f('ix_discos_code'), table_name='discos')
    op.create_unique_constraint('discos_code_key', 'discos', ['code'])
    # ### end Alembic commands ###
